source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.4.4"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.0"
# gem "importmap-rails" # Not needed for API-only app
# gem "turbo-rails" # Not needed for API-only app
# gem "stimulus-rails" # Not needed for API-only app
gem "jbuilder"
gem "redis", "~> 4.0"
gem "bootsnap", require: false
gem "image_processing", "~> 1.2"
gem "bcrypt", "~> 3.1.7"
gem "jwt"
gem "rack-cors"
gem "devise"
gem "devise-jwt"
gem "active_model_serializers"
gem "sidekiq"
gem "kaminari"
gem "httparty"
gem "roo", "~> 2.10.0"

# Video processing
gem "streamio-ffmpeg"
gem "tzinfo-data"

# Calendar integration


group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "rspec-rails"
  gem "factory_bot_rails"
end

group :development do
  gem "web-console"
end

gem 'pundit'
