server {
    listen 80;
    server_name bugzera.shop www.bugzera.shop;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name bugzera.shop www.bugzera.shop;

    ssl_certificate /etc/letsencrypt/live/bugzera.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bugzera.shop/privkey.pem;

    location /api/ {
        proxy_pass http://backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://frontend:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
